In [4]:
import os
import pandas as pd

In [114]:
country_tweets = {}
directory = r'Classified_Country_tweets'
for filename in os.listdir(directory):
    df = pd.read_csv(directory+"/"+filename)
    pos_list = [str(tweet) for tweet in list(df['Positive']) if(str(tweet) != 'nan')]
    neg_list = [str(tweet) for tweet in list(df['Negative']) if(str(tweet) != 'nan')]
    
    if(len(pos_list) > 0 and len(neg_list) > 0):
        if(pos_list[0].isnumeric() and neg_list[0].isnumeric()):
            pos_neg_count = {"positive":len(pos_list)-1,"negative":len(neg_list)-1}
        else:
            pos_neg_count = {"positive":len(pos_list),"negative":len(neg_list)}
    elif(len(pos_list) > 0):
#     print(type(neg_list[0]))
        if(pos_list[0].isnumeric()):
            pos_neg_count = {"positive":len(pos_list)-1,"negative":len(neg_list)}
        else:
            pos_neg_count = {"positive":len(pos_list),"negative":len(neg_list)}
    elif(len(neg_list) > 0):
        if(neg_list[0].isnumeric()):
            pos_neg_count = {"positive":len(pos_list),"negative":len(neg_list)-1}
        else:
            pos_neg_count = {"positive":len(pos_list),"negative":len(neg_list)}
    else:
        pass
    
    country_tweets[filename[0:-4]] = pos_neg_count

In [115]:
country_tweets

{'afghanistan': {'positive': 29, 'negative': 5},
 'albania': {'positive': 134, 'negative': 62},
 'algeria': {'positive': 13, 'negative': 7},
 'american samoa': {'positive': 0, 'negative': 1},
 'andorra': {'positive': 4, 'negative': 1},
 'angola': {'positive': 5, 'negative': 1},
 'anguilla': {'positive': 1, 'negative': 0},
 'antigua and barbuda': {'positive': 2, 'negative': 3},
 'argentina': {'positive': 383, 'negative': 202},
 'armenia': {'positive': 3, 'negative': 16},
 'aruba': {'positive': 2, 'negative': 2},
 'australia': {'positive': 2444, 'negative': 1891},
 'austria': {'positive': 27, 'negative': 72},
 'azerbaijan': {'positive': 454, 'negative': 78},
 'bahamas': {'positive': 11, 'negative': 14},
 'bahrain': {'positive': 18, 'negative': 13},
 'bangladesh': {'positive': 77, 'negative': 94},
 'barbados': {'positive': 14, 'negative': 9},
 'belgium': {'positive': 210, 'negative': 125},
 'belize': {'positive': 6, 'negative': 7},
 'benin': {'positive': 2, 'negative': 1},
 'bermuda': {'positive': 16, 'negative': 32},
 'bhutan': {'positive': 1, 'negative': 1},
 'bolivia': {'positive': 7, 'negative': 29},
 'bosnia and herzegovina': {'positive': 1, 'negative': 14},
 'botswana': {'positive': 283, 'negative': 154},
 'brazil': {'positive': 265, 'negative': 163},
 'british virgin islands': {'positive': 2, 'negative': 1},
 'brunei': {'positive': 1, 'negative': 2},
 'bulgaria': {'positive': 11, 'negative': 62},
 'burkina faso': {'positive': 47, 'negative': 25},
 'burundi': {'positive': 3, 'negative': 2},
 'cambodia': {'positive': 11, 'negative': 9},
 'cameroon': {'positive': 674, 'negative': 104},
 'canada': {'positive': 7662, 'negative': 5062},
 'cape verde': {'positive': 3, 'negative': 5},
 'cayman islands': {'positive': 121, 'negative': 117},
 'central african republic': {'positive': 28, 'negative': 5},
 'chad': {'positive': 1, 'negative': 0},
 'china': {'positive': 365, 'negative': 294},
 'christmas island': {'positive': 2, 'negative': 1},
 'colombia': {'positive': 157, 'negative': 505},
 'cook islands': {'positive': 1, 'negative': 1},
 'costa rica': {'positive': 8, 'negative': 101},
 'croatia': {'positive': 2, 'negative': 5},
 'cuba': {'positive': 42, 'negative': 12},
 'curacao': {'positive': 1, 'negative': 0},
 'cyprus': {'positive': 10, 'negative': 17},
 'czech republic': {'positive': 12, 'negative': 30},
 'democratic republic of the congo': {'positive': 3, 'negative': 3},
 'denmark': {'positive': 89, 'negative': 24},
 'djibouti': {'positive': 4, 'negative': 2},
 'dominica': {'positive': 0, 'negative': 1},
 'dominican republic': {'positive': 25, 'negative': 11},
 'east timor': {'positive': 2, 'negative': 5},
 'ecuador': {'positive': 31, 'negative': 27},
 'egypt': {'positive': 113, 'negative': 66},
 'el salvador': {'positive': 8, 'negative': 6},
 'equatorial guinea': {'positive': 3, 'negative': 3},
 'eritrea': {'positive': 5, 'negative': 2},
 'ethiopia': {'positive': 41, 'negative': 6},
 'falkland islands': {'positive': 1, 'negative': 1},
 'faroe islands': {'positive': 1, 'negative': 1},
 'fiji': {'positive': 214, 'negative': 145},
 'finland': {'positive': 81, 'negative': 11},
 'france': {'positive': 357, 'negative': 223},
 'french polynesia': {'positive': 0, 'negative': 1},
 'gabon': {'positive': 616, 'negative': 400},
 'gambia': {'positive': 3, 'negative': 6},
 'georgia': {'positive': 88, 'negative': 42},
 'germany': {'positive': 149, 'negative': 582},
 'ghana': {'positive': 757, 'negative': 470},
 'gibraltar': {'positive': 1, 'negative': 2},
 'greece': {'positive': 58, 'negative': 48},
 'greenland': {'positive': 1, 'negative': 1},
 'grenada': {'positive': 2, 'negative': 1},
 'guadeloupe': {'positive': 1, 'negative': 0},
 'guam': {'positive': 7, 'negative': 4},
 'guatemala': {'positive': 24, 'negative': 1},
 'belarus': {'positive': 2, 'negative': 5},
 'chile': {'positive': 77, 'negative': 233},
 'estonia': {'positive': 39, 'negative': 12},
 'guernsey': {'positive': 4, 'negative': 1},
 'japan': {'positive': 716, 'negative': 144},
 'marshall islands': {'positive': 1, 'negative': 0},
 'niger': {'positive': 77, 'negative': 45},
 'puerto rico': {'positive': 16, 'negative': 74},
 'slovakia': {'positive': 7, 'negative': 6},
 'togo': {'positive': 5, 'negative': 3},
 'guinea-bissau': {'positive': 1, 'negative': 0},
 'guinea': {'positive': 3, 'negative': 1},
 'guyana': {'positive': 6, 'negative': 6},
 'haiti': {'positive': 7, 'negative': 1},
 'honduras': {'positive': 7, 'negative': 6},
 'hong kong': {'positive': 425, 'negative': 94},
 'hungary': {'positive': 24, 'negative': 17},
 'iceland': {'positive': 6, 'negative': 41},
 'india': {'positive': 4330, 'negative': 1703},
 'indonesia': {'positive': 275, 'negative': 156},
 'iran': {'positive': 9, 'negative': 42},
 'iraq': {'positive': 8, 'negative': 26},
 'ireland': {'positive': 238, 'negative': 758},
 'isle of man': {'positive': 4, 'negative': 9},
 'israel': {'positive': 244, 'negative': 918},
 'italy': {'positive': 295, 'negative': 163},
 'ivory coast': {'positive': 6, 'negative': 19},
 'jamaica': {'positive': 83, 'negative': 280},
 'jersey': {'positive': 13, 'negative': 12},
 'jordan': {'positive': 13, 'negative': 15},
 'kazakhstan': {'positive': 1, 'negative': 1},
 'kenya': {'positive': 369, 'negative': 175},
 'kosovo': {'positive': 0, 'negative': 1},
 'kuwait': {'positive': 40, 'negative': 8},
 'kyrgyzstan': {'positive': 3, 'negative': 1},
 'latvia': {'positive': 6, 'negative': 5},
 'lebanon': {'positive': 42, 'negative': 20},
 'lesotho': {'positive': 1, 'negative': 1},
 'liberia': {'positive': 144, 'negative': 10},
 'libya': {'positive': 11, 'negative': 3},
 'liechtenstein': {'positive': 6, 'negative': 2},
 'lithuania': {'positive': 19, 'negative': 9},
 'luxembourg': {'positive': 15, 'negative': 7},
 'macao': {'positive': 221, 'negative': 149},
 'macedonia': {'positive': 2, 'negative': 2},
 'madagascar': {'positive': 1, 'negative': 1},
 'malawi': {'positive': 10, 'negative': 7},
 'malaysia': {'positive': 296, 'negative': 175},
 'maldives': {'positive': 45, 'negative': 11},
 'mali': {'positive': 142, 'negative': 103},
 'malta': {'positive': 36, 'negative': 37},
 'martinique': {'positive': 1, 'negative': 0},
 'mexico': {'positive': 57, 'negative': 263},
 'micronesia': {'positive': 1, 'negative': 0},
 'moldova': {'positive': 1, 'negative': 1},
 'monaco': {'positive': 8, 'negative': 5},
 'mongolia': {'positive': 71, 'negative': 240},
 'montenegro': {'positive': 44, 'negative': 21},
 'montserrat': {'positive': 53, 'negative': 22},
 'morocco': {'positive': 620, 'negative': 349},
 'mozambique': {'positive': 2, 'negative': 7},
 'myanmar': {'positive': 7, 'negative': 5},
 'namibia': {'positive': 7, 'negative': 9},
 'nepal': {'positive': 66, 'negative': 43},
 'netherlands': {'positive': 97, 'negative': 326},
 'new caledonia': {'positive': 150, 'negative': 515},
 'new zealand': {'positive': 485, 'negative': 99},
 'nicaragua': {'positive': 8, 'negative': 16},
 'nigeria': {'positive': 426, 'negative': 1497},
 'norfolk island': {'positive': 2, 'negative': 1},
 'north korea': {'positive': 2, 'negative': 7},
 'northern mariana islands': {'positive': 3, 'negative': 1},
 'norway': {'positive': 60, 'negative': 62},
 'oman': {'positive': 38, 'negative': 1},
 'pakistan': {'positive': 964, 'negative': 246},
 'palau': {'positive': 1, 'negative': 1},
 'palestinian territory': {'positive': 4, 'negative': 6},
 'panama': {'positive': 632, 'negative': 410},
 'papua new guinea': {'positive': 5, 'negative': 23},
 'paraguay': {'positive': 10, 'negative': 3},
 'peru': {'positive': 49, 'negative': 54},
 'philippines': {'positive': 824, 'negative': 201},
 'pitcairn': {'positive': 0, 'negative': 1},
 'poland': {'positive': 55, 'negative': 30},
 'portugal': {'positive': 137, 'negative': 25},
 'qatar': {'positive': 29, 'negative': 69},
 'republic of the congo': {'positive': 1, 'negative': 4},
 'reunion': {'positive': 1, 'negative': 0},
 'romania': {'positive': 33, 'negative': 8},
 'russia': {'positive': 61, 'negative': 37},
 'rwanda': {'positive': 31, 'negative': 11},
 'saint helena': {'positive': 3, 'negative': 1},
 'saint kitts and nevis': {'positive': 1, 'negative': 1},
 'saint lucia': {'positive': 7, 'negative': 7},
 'saint vincent and the grenadines': {'positive': 4, 'negative': 6},
 'samoa': {'positive': 2, 'negative': 2},
 'san marino': {'positive': 1, 'negative': 1},
 'saudi arabia': {'positive': 94, 'negative': 42},
 'senegal': {'positive': 8, 'negative': 16},
 'serbia': {'positive': 2, 'negative': 12},
 'seychelles': {'positive': 49, 'negative': 198},
 'sierra leone': {'positive': 13, 'negative': 4},
 'singapore': {'positive': 269, 'negative': 203},
 'sint maarten': {'positive': 1, 'negative': 0},
 'slovenia': {'positive': 3, 'negative': 4},
 'somalia': {'positive': 126, 'negative': 90},
 'south africa': {'positive': 191, 'negative': 570},
 'south korea': {'positive': 27, 'negative': 112},
 'south sudan': {'positive': 7, 'negative': 19},
 'spain': {'positive': 145, 'negative': 555},
 'sri lanka': {'positive': 33, 'negative': 103},
 'sudan': {'positive': 28, 'negative': 16},
 'suriname': {'positive': 1, 'negative': 0},
 'svalbard and jan mayen': {'positive': 1, 'negative': 3},
 'swaziland': {'positive': 2, 'negative': 1},
 'sweden': {'positive': 105, 'negative': 95},
 'switzerland': {'positive': 302, 'negative': 180},
 'syria': {'positive': 4, 'negative': 5},
 'taiwan': {'positive': 71, 'negative': 52},
 'tajikistan': {'positive': 1, 'negative': 1},
 'tanzania': {'positive': 18, 'negative': 42},
 'thailand': {'positive': 55, 'negative': 265},
 'tonga': {'positive': 5, 'negative': 2},
 'trinidad and tobago': {'positive': 46, 'negative': 36},
 'tunisia': {'positive': 87, 'negative': 342},
 'turkey': {'positive': 452, 'negative': 1607},
 'turkmenistan': {'positive': 6, 'negative': 3},
 'turks and caicos islands': {'positive': 2, 'negative': 1},
 'u.s. virgin islands': {'positive': 1, 'negative': 1},
 'uganda': {'positive': 116, 'negative': 54},
 'ukraine': {'positive': 30, 'negative': 4},
 'united arab emirates': {'positive': 120, 'negative': 311},
 'united kingdom': {'positive': 5058, 'negative': 3240},
 'united states': {'positive': 7911, 'negative': 29784},
 'uruguay': {'positive': 5, 'negative': 26},
 'uzbekistan': {'positive': 1, 'negative': 1},
 'vanuatu': {'positive': 0, 'negative': 1},
 'vatican': {'positive': 2, 'negative': 3},
 'venezuela': {'positive': 139, 'negative': 72},
 'vietnam': {'positive': 77, 'negative': 5},
 'western sahara': {'positive': 2, 'negative': 1},
 'yemen': {'positive': 8, 'negative': 5},
 'zambia': {'positive': 14, 'negative': 8},
 'zimbabwe': {'positive': 62, 'negative': 11}}

In [116]:
pd.DataFrame(country_tweets)

,afghanistan,albania,algeria,american samoa,andorra,angola,anguilla,antigua and barbuda,argentina,armenia,...,uruguay,uzbekistan,vanuatu,vatican,venezuela,vietnam,western sahara,yemen,zambia,zimbabwe
positive,29,134,13,0,4,5,1,2,383,3,...,5,1,0,2,139,77,2,8,14,62
negative,5,62,7,1,1,1,0,3,202,16,...,26,1,1,3,72,5,1,5,8,11

In [117]:
country_tweets = {}
directory = r'Classified_Country_tweets'
pos_count = {}
neg_count = {}
for filename in os.listdir(directory):
    df = pd.read_csv(directory+"/"+filename)
    pos_list = [str(tweet) for tweet in list(df['Positive']) if(str(tweet) != 'nan')]
    neg_list = [str(tweet) for tweet in list(df['Negative']) if(str(tweet) != 'nan')]
    
    if(len(pos_list) > 0 and len(neg_list) > 0):
        if(pos_list[0].isnumeric() and neg_list[0].isnumeric()):
            pos_count[filename[0:-4]] = len(pos_list)-1
            neg_count[filename[0:-4]] = len(neg_list)-1
        else:
            pos_count[filename[0:-4]] = len(pos_list)
            neg_count[filename[0:-4]] = len(neg_list)
    elif(len(pos_list) > 0):
#     print(type(neg_list[0]))
        if(pos_list[0].isnumeric()):
            pos_count[filename[0:-4]] = len(pos_list)-1
            neg_count[filename[0:-4]] = len(neg_list)
        else:
            pos_count[filename[0:-4]] = len(pos_list)
            neg_count[filename[0:-4]] = len(neg_list)
    elif(len(neg_list) > 0):
        if(neg_list[0].isnumeric()):
            pos_count[filename[0:-4]] = len(pos_list)
            neg_count[filename[0:-4]] = len(neg_list)-1
        else:
            pos_count[filename[0:-4]] = len(pos_list)
            neg_count[filename[0:-4]] = len(neg_list)
    else:
        pass
    
    country_tweets['positive'] = pos_count
    country_tweets['negative'] = neg_count

In [118]:
country_tweets

{'positive': {'afghanistan': 29,
  'albania': 134,
  'algeria': 13,
  'american samoa': 0,
  'andorra': 4,
  'angola': 5,
  'anguilla': 1,
  'antigua and barbuda': 2,
  'argentina': 383,
  'armenia': 3,
  'aruba': 2,
  'australia': 2444,
  'austria': 27,
  'azerbaijan': 454,
  'bahamas': 11,
  'bahrain': 18,
  'bangladesh': 77,
  'barbados': 14,
  'belgium': 210,
  'belize': 6,
  'benin': 2,
  'bermuda': 16,
  'bhutan': 1,
  'bolivia': 7,
  'bosnia and herzegovina': 1,
  'botswana': 283,
  'brazil': 265,
  'british virgin islands': 2,
  'brunei': 1,
  'bulgaria': 11,
  'burkina faso': 47,
  'burundi': 3,
  'cambodia': 11,
  'cameroon': 674,
  'canada': 7662,
  'cape verde': 3,
  'cayman islands': 121,
  'central african republic': 28,
  'chad': 1,
  'china': 365,
  'christmas island': 2,
  'colombia': 157,
  'cook islands': 1,
  'costa rica': 8,
  'croatia': 2,
  'cuba': 42,
  'curacao': 1,
  'cyprus': 10,
  'czech republic': 12,
  'democratic republic of the congo': 3,
  'denmark': 89,
  'djibouti': 4,
  'dominica': 0,
  'dominican republic': 25,
  'east timor': 2,
  'ecuador': 31,
  'egypt': 113,
  'el salvador': 8,
  'equatorial guinea': 3,
  'eritrea': 5,
  'ethiopia': 41,
  'falkland islands': 1,
  'faroe islands': 1,
  'fiji': 214,
  'finland': 81,
  'france': 357,
  'french polynesia': 0,
  'gabon': 616,
  'gambia': 3,
  'georgia': 88,
  'germany': 149,
  'ghana': 757,
  'gibraltar': 1,
  'greece': 58,
  'greenland': 1,
  'grenada': 2,
  'guadeloupe': 1,
  'guam': 7,
  'guatemala': 24,
  'belarus': 2,
  'chile': 77,
  'estonia': 39,
  'guernsey': 4,
  'japan': 716,
  'marshall islands': 1,
  'niger': 77,
  'puerto rico': 16,
  'slovakia': 7,
  'togo': 5,
  'guinea-bissau': 1,
  'guinea': 3,
  'guyana': 6,
  'haiti': 7,
  'honduras': 7,
  'hong kong': 425,
  'hungary': 24,
  'iceland': 6,
  'india': 4330,
  'indonesia': 275,
  'iran': 9,
  'iraq': 8,
  'ireland': 238,
  'isle of man': 4,
  'israel': 244,
  'italy': 295,
  'ivory coast': 6,
  'jamaica': 83,
  'jersey': 13,
  'jordan': 13,
  'kazakhstan': 1,
  'kenya': 369,
  'kosovo': 0,
  'kuwait': 40,
  'kyrgyzstan': 3,
  'latvia': 6,
  'lebanon': 42,
  'lesotho': 1,
  'liberia': 144,
  'libya': 11,
  'liechtenstein': 6,
  'lithuania': 19,
  'luxembourg': 15,
  'macao': 221,
  'macedonia': 2,
  'madagascar': 1,
  'malawi': 10,
  'malaysia': 296,
  'maldives': 45,
  'mali': 142,
  'malta': 36,
  'martinique': 1,
  'mexico': 57,
  'micronesia': 1,
  'moldova': 1,
  'monaco': 8,
  'mongolia': 71,
  'montenegro': 44,
  'montserrat': 53,
  'morocco': 620,
  'mozambique': 2,
  'myanmar': 7,
  'namibia': 7,
  'nepal': 66,
  'netherlands': 97,
  'new caledonia': 150,
  'new zealand': 485,
  'nicaragua': 8,
  'nigeria': 426,
  'norfolk island': 2,
  'north korea': 2,
  'northern mariana islands': 3,
  'norway': 60,
  'oman': 38,
  'pakistan': 964,
  'palau': 1,
  'palestinian territory': 4,
  'panama': 632,
  'papua new guinea': 5,
  'paraguay': 10,
  'peru': 49,
  'philippines': 824,
  'pitcairn': 0,
  'poland': 55,
  'portugal': 137,
  'qatar': 29,
  'republic of the congo': 1,
  'reunion': 1,
  'romania': 33,
  'russia': 61,
  'rwanda': 31,
  'saint helena': 3,
  'saint kitts and nevis': 1,
  'saint lucia': 7,
  'saint vincent and the grenadines': 4,
  'samoa': 2,
  'san marino': 1,
  'saudi arabia': 94,
  'senegal': 8,
  'serbia': 2,
  'seychelles': 49,
  'sierra leone': 13,
  'singapore': 269,
  'sint maarten': 1,
  'slovenia': 3,
  'somalia': 126,
  'south africa': 191,
  'south korea': 27,
  'south sudan': 7,
  'spain': 145,
  'sri lanka': 33,
  'sudan': 28,
  'suriname': 1,
  'svalbard and jan mayen': 1,
  'swaziland': 2,
  'sweden': 105,
  'switzerland': 302,
  'syria': 4,
  'taiwan': 71,
  'tajikistan': 1,
  'tanzania': 18,
  'thailand': 55,
  'tonga': 5,
  'trinidad and tobago': 46,
  'tunisia': 87,
  'turkey': 452,
  'turkmenistan': 6,
  'turks and caicos islands': 2,
  'u.s. virgin islands': 1,
  'uganda': 116,
  'ukraine': 30,
  'united arab emirates': 120,
  'united kingdom': 5058,
  'united states': 7911,
  'uruguay': 5,
  'uzbekistan': 1,
  'vanuatu': 0,
  'vatican': 2,
  'venezuela': 139,
  'vietnam': 77,
  'western sahara': 2,
  'yemen': 8,
  'zambia': 14,
  'zimbabwe': 62},
 'negative': {'afghanistan': 5,
  'albania': 62,
  'algeria': 7,
  'american samoa': 1,
  'andorra': 1,
  'angola': 1,
  'anguilla': 0,
  'antigua and barbuda': 3,
  'argentina': 202,
  'armenia': 16,
  'aruba': 2,
  'australia': 1891,
  'austria': 72,
  'azerbaijan': 78,
  'bahamas': 14,
  'bahrain': 13,
  'bangladesh': 94,
  'barbados': 9,
  'belgium': 125,
  'belize': 7,
  'benin': 1,
  'bermuda': 32,
  'bhutan': 1,
  'bolivia': 29,
  'bosnia and herzegovina': 14,
  'botswana': 154,
  'brazil': 163,
  'british virgin islands': 1,
  'brunei': 2,
  'bulgaria': 62,
  'burkina faso': 25,
  'burundi': 2,
  'cambodia': 9,
  'cameroon': 104,
  'canada': 5062,
  'cape verde': 5,
  'cayman islands': 117,
  'central african republic': 5,
  'chad': 0,
  'china': 294,
  'christmas island': 1,
  'colombia': 505,
  'cook islands': 1,
  'costa rica': 101,
  'croatia': 5,
  'cuba': 12,
  'curacao': 0,
  'cyprus': 17,
  'czech republic': 30,
  'democratic republic of the congo': 3,
  'denmark': 24,
  'djibouti': 2,
  'dominica': 1,
  'dominican republic': 11,
  'east timor': 5,
  'ecuador': 27,
  'egypt': 66,
  'el salvador': 6,
  'equatorial guinea': 3,
  'eritrea': 2,
  'ethiopia': 6,
  'falkland islands': 1,
  'faroe islands': 1,
  'fiji': 145,
  'finland': 11,
  'france': 223,
  'french polynesia': 1,
  'gabon': 400,
  'gambia': 6,
  'georgia': 42,
  'germany': 582,
  'ghana': 470,
  'gibraltar': 2,
  'greece': 48,
  'greenland': 1,
  'grenada': 1,
  'guadeloupe': 0,
  'guam': 4,
  'guatemala': 1,
  'belarus': 5,
  'chile': 233,
  'estonia': 12,
  'guernsey': 1,
  'japan': 144,
  'marshall islands': 0,
  'niger': 45,
  'puerto rico': 74,
  'slovakia': 6,
  'togo': 3,
  'guinea-bissau': 0,
  'guinea': 1,
  'guyana': 6,
  'haiti': 1,
  'honduras': 6,
  'hong kong': 94,
  'hungary': 17,
  'iceland': 41,
  'india': 1703,
  'indonesia': 156,
  'iran': 42,
  'iraq': 26,
  'ireland': 758,
  'isle of man': 9,
  'israel': 918,
  'italy': 163,
  'ivory coast': 19,
  'jamaica': 280,
  'jersey': 12,
  'jordan': 15,
  'kazakhstan': 1,
  'kenya': 175,
  'kosovo': 1,
  'kuwait': 8,
  'kyrgyzstan': 1,
  'latvia': 5,
  'lebanon': 20,
  'lesotho': 1,
  'liberia': 10,
  'libya': 3,
  'liechtenstein': 2,
  'lithuania': 9,
  'luxembourg': 7,
  'macao': 149,
  'macedonia': 2,
  'madagascar': 1,
  'malawi': 7,
  'malaysia': 175,
  'maldives': 11,
  'mali': 103,
  'malta': 37,
  'martinique': 0,
  'mexico': 263,
  'micronesia': 0,
  'moldova': 1,
  'monaco': 5,
  'mongolia': 240,
  'montenegro': 21,
  'montserrat': 22,
  'morocco': 349,
  'mozambique': 7,
  'myanmar': 5,
  'namibia': 9,
  'nepal': 43,
  'netherlands': 326,
  'new caledonia': 515,
  'new zealand': 99,
  'nicaragua': 16,
  'nigeria': 1497,
  'norfolk island': 1,
  'north korea': 7,
  'northern mariana islands': 1,
  'norway': 62,
  'oman': 1,
  'pakistan': 246,
  'palau': 1,
  'palestinian territory': 6,
  'panama': 410,
  'papua new guinea': 23,
  'paraguay': 3,
  'peru': 54,
  'philippines': 201,
  'pitcairn': 1,
  'poland': 30,
  'portugal': 25,
  'qatar': 69,
  'republic of the congo': 4,
  'reunion': 0,
  'romania': 8,
  'russia': 37,
  'rwanda': 11,
  'saint helena': 1,
  'saint kitts and nevis': 1,
  'saint lucia': 7,
  'saint vincent and the grenadines': 6,
  'samoa': 2,
  'san marino': 1,
  'saudi arabia': 42,
  'senegal': 16,
  'serbia': 12,
  'seychelles': 198,
  'sierra leone': 4,
  'singapore': 203,
  'sint maarten': 0,
  'slovenia': 4,
  'somalia': 90,
  'south africa': 570,
  'south korea': 112,
  'south sudan': 19,
  'spain': 555,
  'sri lanka': 103,
  'sudan': 16,
  'suriname': 0,
  'svalbard and jan mayen': 3,
  'swaziland': 1,
  'sweden': 95,
  'switzerland': 180,
  'syria': 5,
  'taiwan': 52,
  'tajikistan': 1,
  'tanzania': 42,
  'thailand': 265,
  'tonga': 2,
  'trinidad and tobago': 36,
  'tunisia': 342,
  'turkey': 1607,
  'turkmenistan': 3,
  'turks and caicos islands': 1,
  'u.s. virgin islands': 1,
  'uganda': 54,
  'ukraine': 4,
  'united arab emirates': 311,
  'united kingdom': 3240,
  'united states': 29784,
  'uruguay': 26,
  'uzbekistan': 1,
  'vanuatu': 1,
  'vatican': 3,
  'venezuela': 72,
  'vietnam': 5,
  'western sahara': 1,
  'yemen': 5,
  'zambia': 8,
  'zimbabwe': 11}}

In [119]:
pd.DataFrame(country_tweets)

                positive  negative
afghanistan           29         5
albania              134        62
algeria               13         7
american samoa         0         1
andorra                4         1
...                  ...       ...
vietnam               77         5
western sahara         2         1
yemen                  8         5
zambia                14         8
zimbabwe              62        11

[223 rows x 2 columns]